[project]
name = "Logist"
version = "0.1.0"
description = "Logist manage app"
readme = "README.md"
requires-python = "==3.12.11"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.117.1",
    "psycopg>=3.2.10",
    "psycopg-pool>=3.2.6",
    "pyjwt>=2.10.1",
]
